/**
 * Définition de toutes les catégories de fiches du wiki.
 *
 * Chaque catégorie a :
 * - label   : nom affiché
 * - icon    : emoji
 * - color   : couleur d'accent (HEX)
 * - fields  : liste des champs de la fiche
 *
 * Un champ a :
 * - key     : identifiant interne (utilisé pour stocker la valeur)
 * - label   : libellé affiché
 * - type    : type d'input (text, textarea, select, affiliations, famille, etc.)
 * - group   : "general" → affiché dans la colonne info, sinon dans le corps
 * - options : (pour type="select") liste des valeurs possibles
 */

import {
  LIEU_TYPES,
  STATUT_OPTIONS,
  DYNASTY_STATUS_OPTIONS,
  RECIT_TYPES,
} from './options';

export const CATEGORIES = {
  personnage: {
    label: 'Personnages',
    icon: '👤',
    color: '#c9a84c',
    fields: [
      { key: 'age', label: 'Âge', type: 'text', group: 'general' },
      { key: 'taille', label: 'Taille', type: 'text', group: 'general' },
      { key: 'villeNatale', label: 'Ville natale', type: 'text', group: 'general' },
      { key: 'villeResidence', label: 'Résidence', type: 'text', group: 'general' },
      { key: 'surnom', label: 'Surnom', type: 'text', group: 'general' },
      { key: 'titres', label: 'Titres', type: 'text', group: 'general' },
      { key: 'profession', label: 'Profession', type: 'text', group: 'general' },
      {
        key: 'dynastieFamiliale',
        label: 'Dynastie familiale',
        type: 'multiSearchDynastie',
        group: 'general',
      },
      { key: 'affiliations', label: 'Affiliations', type: 'affiliations', group: 'general' },
      {
        key: 'cultureEthnie',
        label: 'Culture / Ethnie',
        type: 'multiSearchCulture',
        group: 'general',
      },
      { key: 'religion', label: 'Religion', type: 'text', group: 'general' },
      {
        key: 'statut',
        label: 'Statut',
        type: 'select',
        options: STATUT_OPTIONS,
        group: 'general',
      },
      { key: 'apparence', label: 'Apparence physique', type: 'textarea' },
      { key: 'caractere', label: 'Caractère', type: 'textarea' },
      { key: 'qualites', label: 'Qualités', type: 'text' },
      { key: 'defauts', label: 'Défauts', type: 'text' },
      { key: 'valeurs', label: 'Valeurs', type: 'text' },
      { key: 'croyances', label: 'Croyances', type: 'text' },
      { key: 'passe', label: 'Passé et histoire', type: 'textarea' },
      { key: 'famille', label: 'Famille', type: 'famille' },
      { key: 'motivations', label: 'Motivations', type: 'textarea' },
      { key: 'objectifs', label: 'Objectifs', type: 'textarea' },
      { key: 'reves', label: 'Rêves', type: 'text' },
      { key: 'pouvoirs', label: 'Pouvoirs / Compétences', type: 'textarea' },
      { key: 'pointsForts', label: 'Points forts', type: 'text' },
      { key: 'pointsFaibles', label: 'Points faibles', type: 'text' },
      { key: 'personnalite', label: 'Personnalité', type: 'textarea' },
      { key: 'relations', label: 'Relations et ennemis', type: 'textarea' },
      {
        key: 'relationsRoyaumes',
        label: 'Relations Royaumes / Organisations',
        type: 'relationsRoyaumes',
      },
      {
        key: 'personnagesLies',
        label: 'Personnages secondaires liés',
        type: 'personnagesLies',
      },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  nation: {
    label: 'Nations',
    icon: '🏰',
    color: '#7b8fb2',
    fields: [
      { key: 'regime', label: 'Régime', type: 'text', group: 'general' },
      { key: 'dirigeant', label: 'Dirigeant', type: 'searchPersonnage', group: 'general' },
      { key: 'capitale', label: 'Capitale', type: 'searchCapitale', group: 'general' },
      { key: 'devise', label: 'Devise', type: 'text', group: 'general' },
      {
        key: 'religion',
        label: 'Religion(s)',
        type: 'multiSearchReligion',
        group: 'general',
      },
      { key: 'administration', label: 'Administration', type: 'textarea' },
      { key: 'objectif', label: 'Objectif', type: 'textarea' },
      { key: 'forces', label: 'Forces', type: 'textarea' },
      { key: 'faiblesses', label: 'Faiblesses', type: 'textarea' },
      { key: 'origines', label: 'Origines', type: 'textarea' },
      { key: 'geographie', label: 'Géographie', type: 'textarea' },
      { key: 'economie', label: 'Économie', type: 'textarea' },
      { key: 'culture', label: 'Culture', type: 'textarea' },
      { key: 'armee', label: 'Armée', type: 'textarea' },
      { key: 'espionnage', label: "Réseau d'espionnage", type: 'textarea' },
      { key: 'conflits', label: 'Conflits', type: 'textarea' },
      { key: 'alliances', label: 'Alliances', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  organisation: {
    label: 'Organisations',
    icon: '⚔️',
    color: '#9b4d4d',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'fondateur', label: 'Fondateur', type: 'text', group: 'general' },
      { key: 'chef', label: 'Chef actuel', type: 'text', group: 'general' },
      { key: 'siege', label: 'Siège', type: 'text', group: 'general' },
      {
        key: 'affiliationsOrg',
        label: 'Affiliations',
        type: 'multiSearchAll',
        group: 'general',
      },
      { key: 'objectif', label: 'Objectif', type: 'textarea' },
      { key: 'structure', label: 'Structure', type: 'textarea' },
      { key: 'membres', label: 'Membres notables', type: 'textarea' },
      { key: 'methodes', label: 'Méthodes', type: 'textarea' },
      { key: 'ressources', label: 'Ressources', type: 'textarea' },
      { key: 'secrets', label: 'Secrets', type: 'textarea' },
      { key: 'alliances', label: 'Alliances', type: 'textarea' },
      { key: 'ennemis', label: 'Ennemis', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  dynastieFamiliale: {
    label: 'Dynasties familiales',
    icon: '🏠',
    color: '#b8860b',
    fields: [
      { key: 'blason', label: 'Blason / Symbole', type: 'text', group: 'general' },
      { key: 'devise', label: 'Devise familiale', type: 'text', group: 'general' },
      { key: 'nation', label: 'Nation', type: 'searchNation', group: 'general' },
      { key: 'siege', label: 'Siège ancestral', type: 'text', group: 'general' },
      {
        key: 'statutDynastie',
        label: 'Statut',
        type: 'select',
        options: DYNASTY_STATUS_OPTIONS,
        group: 'general',
      },
      {
        key: 'chefDynastie',
        label: 'Chef de la dynastie',
        type: 'searchPersonnage',
        group: 'general',
      },
      { key: 'valeurs', label: 'Valeurs', type: 'text', group: 'general' },
      { key: 'typeStructure', label: 'Type de structure', type: 'text', group: 'general' },
      { key: 'origines', label: 'Origines & Fondation', type: 'textarea' },
      { key: 'lignee', label: 'Lignée & Arbre généalogique', type: 'textarea' },
      { key: 'traditions', label: 'Traditions & Rites dynastiques', type: 'textarea' },
      { key: 'pouvoir', label: 'Pouvoir, Influence & Ressources', type: 'textarea' },
      {
        key: 'relationsAutres',
        label: 'Relations avec les autres Maisons & Factions',
        type: 'textarea',
      },
      { key: 'secrets', label: 'Secrets & Scandales dynastiques', type: 'textarea' },
      { key: 'figuresMarquantes', label: 'Figures marquantes', type: 'textarea' },
      { key: 'etatActuel', label: 'État actuel & Enjeux narratifs', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  religion: {
    label: 'Religions',
    icon: '🕯️',
    color: '#8e6fbf',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'chefSpirituel', label: 'Chef spirituel', type: 'text', group: 'general' },
      { key: 'siegePouvoir', label: 'Siège du pouvoir', type: 'multiSearchLieu', group: 'general' },
      { key: 'divinites', label: 'Divinité(s)', type: 'multiSearchDivinite', group: 'general' },
      { key: 'symboles', label: 'Symboles', type: 'text', group: 'general' },
      { key: 'lieuSacre', label: 'Lieu(x) sacré(s)', type: 'text', group: 'general' },
      { key: 'dogmes', label: 'Dogmes', type: 'textarea' },
      { key: 'rituels', label: 'Rituels', type: 'textarea' },
      { key: 'clerge', label: 'Clergé', type: 'textarea' },
      { key: 'fideles', label: 'Fidèles', type: 'textarea' },
      { key: 'heresies', label: 'Hérésies', type: 'textarea' },
      { key: 'tensions', label: 'Tensions', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  divinite: {
    label: 'Dieux et divinités',
    icon: '✦',
    color: '#e8c547',
    fields: [
      { key: 'pantheon', label: 'Panthéon', type: 'searchReligion', group: 'general' },
      { key: 'domaines', label: 'Domaines', type: 'text', group: 'general' },
      { key: 'surnoms', label: 'Épithètes', type: 'text', group: 'general' },
      { key: 'symboles', label: 'Symboles', type: 'text', group: 'general' },
      { key: 'apparence', label: 'Apparence', type: 'textarea' },
      { key: 'dogme', label: 'Enseignements', type: 'textarea' },
      { key: 'adorateurs', label: 'Adorateurs', type: 'textarea' },
      { key: 'rituels', label: 'Rituels', type: 'textarea' },
      { key: 'mythes', label: 'Mythes', type: 'textarea' },
      { key: 'relationsDiv', label: 'Relations divines', type: 'textarea' },
      { key: 'artefacts', label: 'Artefacts liés', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  titre: {
    label: 'Titres',
    icon: '🎖️',
    color: '#b8945a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'nation', label: 'Nation', type: 'searchNation', group: 'general' },
      { key: 'rang', label: 'Rang', type: 'text', group: 'general' },
      { key: 'symboles', label: 'Insignes', type: 'text', group: 'general' },
      { key: 'privileges', label: 'Privilèges', type: 'textarea' },
      { key: 'obligations', label: 'Obligations', type: 'textarea' },
      { key: 'conditions', label: 'Conditions', type: 'textarea' },
      { key: 'porteurs', label: 'Porteurs', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  mythe: {
    label: 'Mythes & Légendes',
    icon: '📖',
    color: '#a08060',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'origine', label: 'Origine', type: 'text', group: 'general' },
      { key: 'epoque', label: 'Époque', type: 'text', group: 'general' },
      { key: 'protagonistes', label: 'Protagonistes', type: 'textarea' },
      { key: 'recit', label: 'Récit', type: 'textarea' },
      { key: 'morale', label: 'Morale', type: 'textarea' },
      { key: 'verite', label: 'Part de vérité (auteur)', type: 'textarea' },
      { key: 'impactMonde', label: 'Impact', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  formationMilitaire: {
    label: 'Formations militaires',
    icon: '🛡️',
    color: '#6a7f5a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'nation', label: 'Nation', type: 'searchNation', group: 'general' },
      { key: 'commandant', label: 'Commandant', type: 'searchPersonnage', group: 'general' },
      { key: 'effectif', label: 'Effectif', type: 'text', group: 'general' },
      { key: 'basePrincipale', label: 'Base', type: 'text', group: 'general' },
      { key: 'specialite', label: 'Spécialité', type: 'textarea' },
      { key: 'equipement', label: 'Équipement', type: 'textarea' },
      { key: 'structure', label: 'Structure', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'batailles', label: 'Batailles', type: 'textarea' },
      { key: 'reputation', label: 'Réputation', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  sort: {
    label: 'Sorts & Magie',
    icon: '✨',
    color: '#6e5cbf',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'ecole', label: 'École', type: 'text', group: 'general' },
      { key: 'puissance', label: 'Puissance', type: 'text', group: 'general' },
      { key: 'effet', label: 'Effet', type: 'textarea' },
      { key: 'composants', label: 'Composants', type: 'textarea' },
      { key: 'incantation', label: 'Incantation', type: 'textarea' },
      { key: 'cout', label: 'Coût', type: 'textarea' },
      { key: 'utilisateurs', label: 'Utilisateurs', type: 'textarea' },
      { key: 'dangers', label: 'Dangers', type: 'textarea' },
      { key: 'histoire', label: 'Origine', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  technologie: {
    label: 'Technologies',
    icon: '⚙️',
    color: '#7a8a9a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'nation', label: 'Nation', type: 'searchNation', group: 'general' },
      { key: 'inventeur', label: 'Inventeur', type: 'text', group: 'general' },
      { key: 'epoque', label: 'Époque', type: 'text', group: 'general' },
      { key: 'disponibilite', label: 'Rareté', type: 'text', group: 'general' },
      { key: 'fonctionnement', label: 'Fonctionnement', type: 'textarea' },
      { key: 'usages', label: 'Usages', type: 'textarea' },
      { key: 'impact', label: 'Impact', type: 'textarea' },
      { key: 'limites', label: 'Limites', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  langue: {
    label: 'Langues',
    icon: '🗣️',
    color: '#8a7a6a',
    fields: [
      { key: 'famille', label: 'Famille', type: 'text', group: 'general' },
      { key: 'locuteurs', label: 'Locuteurs', type: 'text', group: 'general' },
      { key: 'ecriture', label: 'Écriture', type: 'text', group: 'general' },
      { key: 'statut', label: 'Statut', type: 'text', group: 'general' },
      { key: 'particularites', label: 'Particularités', type: 'textarea' },
      { key: 'expressions', label: 'Expressions', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'dialectes', label: 'Dialectes', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  culture: {
    label: 'Cultures & Ethnies',
    icon: '🎭',
    color: '#a0706a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      {
        key: 'region',
        label: 'Région',
        type: 'multiSearchNationLieu',
        group: 'general',
      },
      { key: 'population', label: 'Population', type: 'text', group: 'general' },
      { key: 'langue', label: 'Langue(s)', type: 'multiSearchLangue', group: 'general' },
      {
        key: 'religion',
        label: 'Religion(s)',
        type: 'multiSearchReligion',
        group: 'general',
      },
      { key: 'traditions', label: 'Traditions', type: 'textarea' },
      { key: 'valeurs', label: 'Valeurs', type: 'textarea' },
      { key: 'art', label: 'Arts', type: 'textarea' },
      { key: 'structure', label: 'Structure sociale', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'tensions', label: 'Tensions', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  document: {
    label: 'Documents',
    icon: '📜',
    color: '#b09070',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'auteur', label: 'Auteur', type: 'text', group: 'general' },
      { key: 'date', label: 'Date', type: 'text', group: 'general' },
      { key: 'destinataire', label: 'Destinataire', type: 'text', group: 'general' },
      { key: 'localisation', label: 'Localisation', type: 'text', group: 'general' },
      { key: 'contenu', label: 'Contenu', type: 'textarea' },
      { key: 'importance', label: 'Importance', type: 'textarea' },
      { key: 'secrets', label: 'Secrets', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  vehicule: {
    label: 'Véhicules',
    icon: '⛵',
    color: '#5a7a8a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'nom', label: 'Nom', type: 'text', group: 'general' },
      { key: 'proprietaire', label: 'Propriétaire', type: 'text', group: 'general' },
      { key: 'nation', label: 'Nation', type: 'searchNation', group: 'general' },
      { key: 'equipage', label: 'Équipage', type: 'text', group: 'general' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'capacites', label: 'Capacités', type: 'textarea' },
      { key: 'armement', label: 'Armement', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  evenement: {
    label: 'Événements',
    icon: '⚡',
    color: '#b07d4b',
    fields: [
      { key: 'date', label: 'Date', type: 'text', group: 'general' },
      { key: 'lieu', label: 'Lieu', type: 'text', group: 'general' },
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'participants', label: 'Participants', type: 'textarea' },
      { key: 'causes', label: 'Causes', type: 'textarea' },
      { key: 'deroulement', label: 'Déroulement', type: 'textarea' },
      { key: 'consequences', label: 'Conséquences', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  animal: {
    label: 'Animaux & Créatures',
    icon: '🐺',
    color: '#6a8a5a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'habitat', label: 'Habitat', type: 'text', group: 'general' },
      { key: 'region', label: 'Région', type: 'text', group: 'general' },
      { key: 'apparence', label: 'Apparence', type: 'textarea' },
      { key: 'comportement', label: 'Comportement', type: 'textarea' },
      { key: 'capacites', label: 'Capacités', type: 'textarea' },
      { key: 'dangers', label: 'Dangers', type: 'textarea' },
      { key: 'utilisations', label: 'Utilisations', type: 'textarea' },
      { key: 'mythes', label: 'Mythes', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  objet: {
    label: 'Objets & Artefacts',
    icon: '👑',
    color: '#d4a24e',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'createur', label: 'Créateur', type: 'text', group: 'general' },
      { key: 'materiaux', label: 'Matériaux', type: 'text', group: 'general' },
      { key: 'porteur', label: 'Porteur', type: 'text', group: 'general' },
      { key: 'localisation', label: 'Localisation', type: 'text', group: 'general' },
      { key: 'origine', label: 'Origine', type: 'textarea' },
      { key: 'pouvoirs', label: 'Pouvoirs', type: 'textarea' },
      { key: 'conditions', label: 'Conditions', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'dangers', label: 'Dangers', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  batiment: {
    label: 'Bâtiments',
    icon: '🏛️',
    color: '#8a8070',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'lieu', label: 'Lieu', type: 'text', group: 'general' },
      { key: 'nation', label: 'Nation', type: 'searchNation', group: 'general' },
      { key: 'proprietaire', label: 'Propriétaire', type: 'text', group: 'general' },
      { key: 'constructeur', label: 'Architecte', type: 'text', group: 'general' },
      { key: 'epoque', label: 'Époque', type: 'text', group: 'general' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'fonction', label: 'Fonction', type: 'textarea' },
      { key: 'occupants', label: 'Occupants', type: 'textarea' },
      { key: 'secrets', label: 'Secrets', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  lieu: {
    label: 'Lieux',
    icon: '🗺️',
    color: '#5a8f6e',
    fields: [
      {
        key: 'typeLieu',
        label: 'Type de lieu',
        type: 'select',
        options: LIEU_TYPES,
        group: 'general',
      },
      { key: 'nation', label: 'Nation', type: 'searchNation', group: 'general' },
      { key: 'population', label: 'Population', type: 'text', group: 'general' },
      { key: 'dirigeant', label: 'Dirigeant', type: 'text', group: 'general' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'pointsInteret', label: "Points d'intérêt", type: 'textarea' },
      { key: 'batimentsNotables', label: 'Bâtiments notables', type: 'textarea' },
      { key: 'economie', label: 'Économie', type: 'textarea' },
      { key: 'culture', label: 'Culture locale', type: 'textarea' },
      { key: 'armee', label: 'Armée', type: 'textarea' },
      { key: 'dangers', label: 'Dangers', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  tradition: {
    label: 'Traditions',
    icon: '🎪',
    color: '#c4956a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'origine', label: 'Origine / Peuple', type: 'text', group: 'general' },
      { key: 'epoque', label: 'Époque', type: 'text', group: 'general' },
      { key: 'lieu', label: 'Lieu', type: 'text', group: 'general' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'rituels', label: 'Rituels associés', type: 'textarea' },
      { key: 'signification', label: 'Signification', type: 'textarea' },
      { key: 'participants', label: 'Participants', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  profession: {
    label: 'Professions',
    icon: '🔨',
    color: '#8a6a5a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'nation', label: 'Nation(s)', type: 'text', group: 'general' },
      { key: 'statut', label: 'Statut social', type: 'text', group: 'general' },
      { key: 'formation', label: 'Formation requise', type: 'text', group: 'general' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'competences', label: 'Compétences', type: 'textarea' },
      { key: 'outils', label: 'Outils / Équipement', type: 'textarea' },
      { key: 'hierarchie', label: 'Hiérarchie / Guildes', type: 'textarea' },
      { key: 'pratiquants', label: 'Pratiquants notables', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  maladie: {
    label: 'Maladies',
    icon: '🦠',
    color: '#7a5a5a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'transmission', label: 'Transmission', type: 'text', group: 'general' },
      { key: 'regions', label: 'Régions touchées', type: 'text', group: 'general' },
      { key: 'mortalite', label: 'Mortalité', type: 'text', group: 'general' },
      { key: 'symptomes', label: 'Symptômes', type: 'textarea' },
      { key: 'traitement', label: 'Traitement', type: 'textarea' },
      { key: 'origine', label: 'Origine', type: 'textarea' },
      { key: 'histoire', label: 'Histoire', type: 'textarea' },
      { key: 'impact', label: 'Impact sur la société', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  arbreVegetal: {
    label: 'Arbres & Végétaux',
    icon: '🌿',
    color: '#5a7a4a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'habitat', label: 'Habitat', type: 'text', group: 'general' },
      { key: 'region', label: 'Région', type: 'text', group: 'general' },
      { key: 'rarete', label: 'Rareté', type: 'text', group: 'general' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'proprietes', label: 'Propriétés', type: 'textarea' },
      { key: 'usages', label: 'Usages', type: 'textarea' },
      { key: 'mythes', label: 'Mythes associés', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  materiau: {
    label: 'Matériaux',
    icon: '💎',
    color: '#6a8a9a',
    fields: [
      { key: 'type', label: 'Type', type: 'text', group: 'general' },
      { key: 'origine', label: 'Origine', type: 'text', group: 'general' },
      { key: 'rarete', label: 'Rareté', type: 'text', group: 'general' },
      { key: 'region', label: "Région d'extraction", type: 'text', group: 'general' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'proprietes', label: 'Propriétés', type: 'textarea' },
      { key: 'usages', label: 'Usages', type: 'textarea' },
      { key: 'valeur', label: 'Valeur commerciale', type: 'textarea' },
      { key: 'roleIntrigue', label: "Rôle dans l'intrigue", type: 'textarea' },
    ],
  },

  recit: {
    label: 'Récits',
    icon: '📕',
    color: '#c45a5a',
    fields: [
      {
        key: 'typeRecit',
        label: 'Type de récit',
        type: 'select',
        options: RECIT_TYPES,
        group: 'general',
      },
      { key: 'numeroTome', label: 'Numéro de tome', type: 'text', group: 'general' },
      { key: 'contenu', label: 'Contenu', type: 'textarea' },
    ],
  },
};

/**
 * Ordre d'affichage des catégories dans le dashboard et les menus.
 */
export const CAT_ORDER = [
  'personnage',
  'nation',
  'organisation',
  'dynastieFamiliale',
  'religion',
  'divinite',
  'titre',
  'mythe',
  'formationMilitaire',
  'sort',
  'technologie',
  'langue',
  'culture',
  'tradition',
  'profession',
  'maladie',
  'arbreVegetal',
  'materiau',
  'document',
  'vehicule',
  'evenement',
  'animal',
  'objet',
  'batiment',
  'lieu',
  'recit',
];
